<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
        <link rel="stylesheet" href="assets/bootstrap/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="assets/bootstrap/dist/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="css/main.css">
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="assets/jquery/dist/jquery.min.js"><\/script>')</script>
    </head>
    <body>
        <!-- Header -->
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <p>&nbsp;</p>
                </div>
            </div>
        </div>
        <!-- end Header -->
        <!-- Nav -->
        <div class="container-fluid">
            <div class="container">
	            <div class="row">
                    <nav class="navbar navbar-default navbar-pink" role="navigation">
					  <div class="container-fluid">
					    <!-- Brand and toggle get grouped for better mobile display -->
					    <div class="navbar-header">
					      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					        <span class="sr-only">Toggle navigation</span>
					        <span class="icon-bar"></span>
					        <span class="icon-bar"></span>
					        <span class="icon-bar"></span>
					      </button>
					      <a class="navbar-brand" href="/">Accueil</a>
					    </div>
					
					    <!-- Collect the nav links, forms, and other content for toggling -->
					    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					      <ul class="nav navbar-nav">
					        <li <?= $this->isActive(""); ?>><a href="">Mon compte</a></li>
					      </ul>
					      <ul class="nav navbar-nav navbar-right">
					      	<li><a href="/logout">Déconnexion</a></li>
					      </ul>
					    </div><!-- /.navbar-collapse -->
					  </div><!-- /.container-fluid -->
					</nav>
	            </div><!-- /.row -->
	        </div><!-- /.container -->
	    </div><!-- /.container-fluid -->
	    <!-- endNav -->
	    <!-- Body -->
        <div class="container">
             <div class="row">
                <?= $this->content ?>
            </div>
        </div>
        <!-- end Body -->
        <!-- Footer 1 -->
        <div class="container-fluid">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <p>&nbsp;</p>
                    </div>
                </div>
            </div>
        </div>
        <!-- end Footer 1 -->
        <script src="assets/bootstrap/dist/js/bootstrap.min.js"></script>
        <script src="js/main.js"></script>

    </body>
</html>
