<?php //if(empty($this->user)) Url::redirect("/home"); ?>
<div class="col-sm-3">
	<form role="form" id="famille" name="famille" method="post">
		<h1 class="text-center">Saisie des familles</h1>
		<div class="form-group">
			<label for="code">Code</label>
			<input type="text" class="form-control data" name="code" id="code" size="30" OnBlur="OnVide('code')">
		</div>
		<div class="form-group">
			<label for="lib">Libellé</label>
			<input type="text" class="form-control data" name="lib" id="lib" onBlur="OnVide('lib')">
		</div>
		<input name="create" id="create" type="submit" value="Valider" class="btn btn-default btn-sm"/>
		<input name="supp" id="supp" type="submit" value="Supprimer" class="btn btn-default btn-sm pull-right"/>

		<!-- ===========================  Partie  Cache   ================================ -->
		<div class='hidden'>
		  <input type="text" id="ident" name="ident">
		</div>
		<!-- ========================== fin div cachée =================================== -->
	</form>
	<div class="text-alert text-center" id="alerte"></div>
	<div class="text-center" id="envoiencours"></div>
</div>
<div class="col-sm-9">
    <table class="table table-bordered table-striped table-condensed test">
    	<thead>
    		<?php foreach($this->entete as $title) : ?>
    		<th><?= $title ?></th>
    		<?php endforeach; ?>
    	</thead>
    	<tbody>
		<?php foreach($this->list as $ligne) : ?>
			<tr>
			<?php foreach($ligne as $key => $cel) : ?>
				<?php if(gettype($key) == 'string') : ?>
					<td><?= $cel ?></td>
				<?php endif; ?>
			<?php endforeach; ?>
			</tr>
		<?php endforeach; ?>
    	</tbody>
    </table>
</div>

