<div class="col-sm-3">
	<h3 class="text-center">Créer un compte</h3>
	<form method="POST" action="">
		<div class="form-group">
    		<label for="nom_ccm">Nom commercial : </label>
    		<input name="nom_ccm" id="nom_ccm" type="text" class="form-control" <?php if(isset($this->inputs)) : ?>value="<?= $this->inputs['nom_ccm']?>"<?php endif; ?>/>
    	</div>
	    <div class="form-group">
    		<label for="pseudo">Pseudo : </label>
    		<input name="pseudo" id="pseudo" type="text" class="form-control" <?php if(isset($this->inputs)) : ?>value="<?= $this->inputs['pseudo']?>"<?php endif; ?>/>
    	</div>
    	<div class="form-group">
    		<label for="email">Adresse mail : </label>
    		<input name="email" id="email" type="text" class="form-control" <?php if(isset($this->inputs)) : ?>value="<?= $this->inputs['email']?>"<?php endif; ?>/>
    	</div>
       <input name="Submit" id="Submit" type="Submit" class="btn btn-default btn-sm"/>
	</form>
	<?php if(!empty($this->errMessages)) : ?>
		<ul class="list-group">
	    	<?php foreach ($this->errMessages as $value) : ?>
				<li class="list-group-item list-group-item-danger"><?= $value ?></li>
	    	<?php endforeach; ?>
	    </ul>
	<?php elseif(!empty($this->validMessages)) : ?>
		<ul class="list-group">
	    	<?php foreach ($this->validMessages as $value) : ?>
				<li class="list-group-item list-group-item-success"><?= $value ?></li>
	    	<?php endforeach; ?>
	    </ul>
	<?php endif; ?>
</div>
<div class="col-sm-9">
	<h3 class="text-center">Liste des clients</h3>
	<table class="table table-striped table-responsive">
		<thead>
			<th>Pseudo</th>
			<th>Pseudo</th>
			<th>E-mail</th>
			<th>Profil</th>
			<th>Actions</th>
		</thead>
		<?php foreach($this->clients as $client) : ?>
		<tr>
			<td><?= $client['pseudo'] ?></td>
			<td><?= $client['email'] ?></td>
			<td><?= $client['profil'] ?></td>
			<td>
				<form action="" method="post" class="inline">
					<input class="hidden" type="text" name="id" value="<?= $client['id_cli'] ?>"/>
					<input class="btn btn-default btn-sm" type="submit" value="Modifier" name="modif" />
				</form>
				<?php if($client['profil'] != "Admin") :  ?>
				<form action="" method="post" class="inline">
					<input class="hidden" type="text" name="id" value="<?= $client['id_cli'] ?>"/>
					<input class="btn btn-danger btn-sm supp" type="button" value="Supprimer" />
					<input class="hidden" disabled="disabled" type="submit" value="Supprimer" name="supp" id="supp" />
				</form>
				<?php endif; ?>
			</td>
		</tr>
		<?php endforeach; ?>
	</table>
</div>