<?php $this->setTitle('Accueil'); ?>
<?php if (FALSE == $this->user) : ?>
<div class="col-sm-4 col-sm-offset-4" id="connexion">
    <h1 class="text-center">Login</h1>
    <?php if (!empty($this->errMessages)) : ?>
    	<ul class="list-group" id="erreurs">
    	<?php foreach ($this->errMessages as $value) : ?>
			<li class="list-group-item list-group-item-danger"><?= $value ?></li>
    	<?php endforeach; ?>
    	</ul>
	<?php endif; ?>
	    <form role="form" method="POST" action="">
	    	<div class="form-group">
	    		<label for="login">Login : </label>
	    		<input name="login" id="login" type="text" class="form-control" <?php if(isset($this->inputs)) : ?>value="<?= $this->inputs['login']?>"<?php endif; ?>/>
	    	</div>
	    	<div class="form-group">
	    		<label for="password">Password : </label>
	    		<input name="password" id="password" type="password" class="form-control" <?php if(isset($this->inputs)) : ?>value="<?= $this->inputs['password']?>"<?php endif; ?>/>
	    	</div>
	       <input name="connect" id="connect" type="Submit" class="btn btn-default btn-sm"/>
	    </form>
	    <p class="text-right"><a href="">Mot de passe oublié ?</a></p>
	    <br>
</div>	    
<?php else : ?>
<div class="col-sm-12">
	<p class="hidden" id="id_client"><?= $this->user['id'] ?></p>
    <h1>Bienvenue <?= $this->user['pseudo'] ?></h1>
    <?php if($this->user['profil'] != 'Admin') : ?>
    <table class="table table-striped table-responsive table-condensed">
    	<thead>
    		<th class="hidden">Code</th>
    		<th>Libellé</th>
			<th>Famille</th>
			<th>Labo</th>
			<th>Prix catalogue</th>
			<th>Prix net</th>
			<th>Nombre de produits par colis</th>
			<th>Quantité de colis</th>
			<th>Total produits</th>
			<th>Total prix</th>
			<th>Actions</th>
    	</thead>
    	<tbody>
    	<?php foreach ($this->produits as $produit) : ?>
    		<tr>
    			<td class="hidden" id="id"><?= $produit['id']; ?></td>
    			<td><?= $produit['lib_prd']; ?></td>
    			<td><?= $produit['lib']; ?></td>
    			<td><?= $produit['nom_lab']; ?></td>
    			<td><?= $produit['prx_cat']; ?></td>
    			<td id="prx_net"><?= $produit['prx_net']; ?></td>
    			<td id="nbp_col"><?= $produit['nbp_col']; ?></td>
    			<td id="input"><input type="text" class="form-control qte" id="qte<?= $produit['id']; ?>" name="qte" /></td>
    			<td id="tot_prd"></td>
    			<td id="tot_prx"></td>
    			<td><input type="button" class="btn btn-default btn-sm command" id="command<?= $produit['id']; ?>" name="command" value="Ajouter au panier"/></td>
    		</tr>
    	<?php endforeach; ?>
    	</tbody>
    </table>
    <div class="text-alert text-center" id="alerte"></div>
	<?php endif; ?>
</div>
<?php endif; ?>

<script type="text/javascript">
$(".qte").keyup(function(e) {
	var elmt = $(e.target.parentNode.parentNode).context;
	var quantite = elmt.children['input'].firstChild.value;
	var prx_net = elmt.children['prx_net'];
	var nbp_col = elmt.children['nbp_col'];
	var tot_prx = elmt.children['tot_prx'];
	var tot_prd = elmt.children['tot_prd'];

	var tot_qte = parseInt(nbp_col.innerHTML) * parseInt(quantite);
	if(isNaN(tot_qte)) {
		tot_qte = 0;
	}
	tot_prd.innerHTML = tot_qte;

	var net = parseFloat(prx_net.innerHTML);
	tot_prx.innerHTML = net * tot_qte;
});
</script>

