<?php if (FALSE == $this->user) : ?>
<div class="col-sm-4 col-sm-offset-4" id="connexion">
    <h1 class="text-center">Login</h1>
    <?php if (!empty($this->errMessages)) : ?>
    	<ul class="list-group" id="erreurs">
    	<?php foreach ($this->errMessages as $value) : ?>
			<li class="list-group-item list-group-item-danger"><?= $value ?></li>
    	<?php endforeach; ?>
    	</ul>
	<?php endif; ?>
	    <form role="form" method="POST" action="">
	    	<div class="form-group">
	    		<label for="login">Login : </label>
	    		<input name="login" id="login" type="text" class="form-control" <?php if(isset($this->inputs)) : ?>value="<?= $this->inputs['login']?>"<?php endif; ?>/>
	    	</div>
	    	<div class="form-group">
	    		<label for="password">Password : </label>
	    		<input name="password" id="password" type="password" class="form-control" <?php if(isset($this->inputs)) : ?>value="<?= $this->inputs['password']?>"<?php endif; ?>/>
	    	</div>
	       <input name="connect" id="connect" type="Submit" class="btn btn-default btn-sm"/>
	    </form>
	    <p class="text-right"><a href="">Mot de passe oublié ?</a></p>
	    <br>
</div>	    
<?php else : ?>
    <h1>Bienvenue <?= $this->user['pseudo'] ?></h1>
<?php endif; ?>
