<div class="col-sm-4 col-sm-offset-4 white">
	<h1 class="text-center">Créer un compte</h1>
	<form method="POST" action="/inscription">
	    <div class="form-group">
    		<label for="login">Login : </label>
    		<input name="login" id="login" type="text" class="form-control" <?php if(isset($this->inputs)) : ?>value="<?= $this->inputs['login']?>"<?php endif; ?>/>
    	</div>
    	<div class="form-group">
    		<label for="email">Adresse mail : </label>
    		<input name="email" id="email" type="text" class="form-control" <?php if(isset($this->inputs)) : ?>value="<?= $this->inputs['email']?>"<?php endif; ?>/>
    	</div>
    	<div class="form-group">
    		<label for="password">Password : </label>
    		<input name="password" id="password" type="password" class="form-control" <?php if(isset($this->inputs)) : ?>value="<?= $this->inputs['password']?>"<?php endif; ?>/>
    	</div>
    	<div class="form-group">
    		<label for="confirm_pass">Confirm password : </label>
    		<input name="confirm_pass" id="confirm_pass" type="password" class="form-control" <?php if(isset($this->inputs)) : ?>value="<?= $this->inputs['confirm_pass']?>"<?php endif; ?>/>
    	</div>
       <input name="Submit" id="Submit" type="Submit" class="btn btn-default btn-sm"/>
	</form>
	<?php if(!empty($this->errMessages)) : ?>
		<ul class="list-group">
	    	<?php foreach ($this->errMessages as $value) : ?>
				<li class="list-group-item list-group-item-danger"><?= $value ?></li>
	    	<?php endforeach; ?>
	    </ul>
	<?php elseif(!empty($this->validMessages)) : ?>
		<ul class="list-group">
	    	<?php foreach ($this->validMessages as $value) : ?>
				<li class="list-group-item list-group-item-success"><?= $value ?></li>
	    	<?php endforeach; ?>
	    </ul>
	<?php endif; ?>
	<p class="text-right"><a href="/home">Se connecter</a></p>
</div>