<?php $this->setTitle('Panier'); ?>
<?php if(empty($this->user)) Url::redirect("/home"); ?>
<div class="col-sm-2">
	<h1 class="text-center">Mes commandes</h1>
</div>
<div class="col-sm-10">
    <h1 class="text-center">Ma commande en cours</h1>
    <?php if(isset($this->lignes)) : ?>
    <table class="table table-striped table-responsive table-condensed">
    	<thead>
    		<th class="hidden">Code</th>
    		<th>Libellé</th>
			<th>Famille</th>
			<th>Labo</th>
			<th>Prix catalogue</th>
			<th>Prix net</th>
			<th>Nombre de produits par colis</th>
			<th>Quantité commandée</th>
			<th>Quantité de colis</th>
			<th>Total produits</th>
			<th>Total prix</th>
			<th>Actions</th>
    	</thead>
    	<tbody>
    	<?php foreach ($this->lignes as $ligne) : ?>
    		<tr>
    			<td class="hidden" id="id"><?= $ligne['produit']['id']; ?></td>
    			<td><?= $ligne['produit']['lib_prd']; ?></td>
    			<td><?= $ligne['produit']['lib']; ?></td>
    			<td><?= $ligne['produit']['nom_lab']; ?></td>
    			<td><?= $ligne['produit']['prx_cat']; ?></td>
    			<td id="prx_net"><?= $ligne['produit']['prx_net']; ?></td>
    			<td id="nbp_col"><?= $ligne['produit']['nbp_col']; ?></td>
    			<td id="qteComandee"><?= $ligne['quantite']; ?></td>
    			<td id="input"><input type="text" class="form-control qte" id="qte<?= $ligne['produit']['id']; ?>" name="qte" /></td>
    			<td id="tot_prd"><?= (int) $ligne['quantite'] * (int) $ligne['produit']['nbp_col']; ?></td>
    			<td id="tot_prx"><?= (int) $ligne['quantite'] * (int) $ligne['produit']['nbp_col'] * (float) $ligne['produit']['prx_net']; ?></td>
    			<td><input type="button" class="btn btn-default btn-sm command" id="command<?= $ligne['produit']['id']; ?>" name="command" value="Modifier"/></td>
    		</tr>
    	<?php endforeach; ?>
    	</tbody>
    	<tfoot>
    		<?php $total = 0;
    		foreach($this->lignes as $ligne) {
    			$sous_total = (int) $ligne['quantite'] * (int) $ligne['produit']['nbp_col'] * (float) $ligne['produit']['prx_net'];
    			$total += $sous_total;
    		} ?>
    		<td class="hidden" id="id_cmd"><?= $this->commande['id_cmd'] ?></td>
    		<td></td>
    		<td></td>
    		<td></td>
    		<td></td>
    		<td></td>
    		<td></td>
    		<td></td>
    		<td></td>
    		<td>Total</td>
    		<td id="total"><?= $total; ?> €</td>
    		<td><input type="button" class="btn btn-default btn-sm" id="validCommand" name="validCommand" value="Valider la commande"/></td>
    	</tfoot>
    </table>
    <?php else : ?>
    	<div class="text-center">Pas de commande en cours...</div>
    <?php endif; ?>
    <div class="text-alert text-center" id="alerte"></div>
</div>
<script type="text/javascript">
if(typeof(Storage) === "undefined") {
    alert('Votre navigateur ne supporte pas le Storage HTML5');
}
$( document ).ready(function() {
	elmts = $('.qte');
	for(var i = 0; i<elmts.length; i++) {
		var tr = elmts[i].parentNode.parentNode;
		var tot_prx = tr.children['tot_prx'].innerHTML;
		var tot_prd = tr.children['tot_prd'].innerHTML;
		sessionStorage.setItem('prx_'+elmts[i].id, tot_prx);
		sessionStorage.setItem('prd_'+elmts[i].id, tot_prd);
	}
});

$('.qte').keyup(function(e) {
	var elmt = $(e.target.parentNode.parentNode).context;
	var id = elmt.children['input'].firstChild.id;
	var quantite = elmt.children['input'].firstChild.value;
	var tot_prx = elmt.children['tot_prx'];
	var tot_prd = elmt.children['tot_prd'];
	if(quantite == '' || isNaN(parseInt(quantite))) {
		tot_prx.innerHTML = sessionStorage.getItem('prx_'+id);
		tot_prd.innerHTML = sessionStorage.getItem('prd_'+id);
	} else {
		var prx_net = elmt.children['prx_net'];
		var nbp_col = elmt.children['nbp_col'];

		var tot_qte = parseInt(nbp_col.innerHTML) * parseInt(quantite);
		tot_prd.innerHTML = tot_qte;

		var net = parseFloat(prx_net.innerHTML);
		tot_prx.innerHTML = net * tot_qte;
	}
});

$('#validCommand').click(function(e) {
	var commande = { 'id_cmd' : $('#id_cmd').html() };
	
	$.ajax({
	  url      : "/panier?context=html",
	  type     : "POST",
	  dataType : "json",
	  data     : commande,
	  success  : function(result) {
		  alert(result['message']);
		  location.reload();
	  }// end success
	});
});
</script>